-- Módulo de Cadastros e Governança de Acessos.
-- Evolui o RBAC existente sem duplicar a fonte de verdade de perfis_acesso.

begin;

alter table public.perfis_acesso
  add column if not exists suspended_until timestamptz,
  add column if not exists version bigint not null default 1;

create index if not exists perfis_acesso_role_status_idx
  on public.perfis_acesso (role, status);

create table if not exists public.equipes (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  descricao text,
  ativo boolean not null default true,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists equipes_nome_uq on public.equipes (lower(nome));
create index if not exists equipes_ativo_nome_idx on public.equipes (ativo, nome);

create table if not exists public.equipe_membros (
  equipe_id uuid not null references public.equipes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  papel_equipe text not null default 'MEMBRO',
  created_at timestamptz not null default now(),
  primary key (equipe_id, user_id)
);

create index if not exists equipe_membros_user_idx
  on public.equipe_membros (user_id, equipe_id);

create table if not exists public.governanca_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid,
  acao text not null,
  entidade text not null,
  entidade_id text,
  antes jsonb,
  depois jsonb,
  created_at timestamptz not null default now()
);

create index if not exists governanca_audit_created_idx
  on public.governanca_audit_log (created_at desc);
create index if not exists governanca_audit_actor_idx
  on public.governanca_audit_log (actor_id, created_at desc);
create index if not exists governanca_audit_entidade_idx
  on public.governanca_audit_log (entidade, entidade_id, created_at desc);

create or replace function public.tecverde_access_profile_active(
  p_status text,
  p_suspended_until timestamptz
)
returns boolean
language sql
stable
set search_path = ''
as $$
  select
    upper(coalesce(p_status, '')) = 'APROVADO'
    or (
      upper(coalesce(p_status, '')) = 'SUSPENSO'
      and p_suspended_until is not null
      and p_suspended_until <= now()
    );
$$;

create or replace function public.tecverde_is_gestao()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
      from public.perfis_acesso p
     where p.user_id = (select auth.uid())
       and upper(coalesce(p.role, '')) in ('GESTAO', 'ADMINISTRADOR', 'ADMIN', 'GESTOR', 'GESTÃO')
       and public.tecverde_access_profile_active(p.status, p.suspended_until)
  );
$$;

revoke all on function public.tecverde_is_gestao() from public, anon;
grant execute on function public.tecverde_is_gestao() to authenticated;

-- Compatibilidade com policies/RPCs legados que já dependem deste helper.
create or replace function public.tecverde_is_principal()
returns boolean
language sql
stable
set search_path = ''
as $$
  select public.tecverde_is_gestao();
$$;

revoke all on function public.tecverde_is_principal() from public, anon;
grant execute on function public.tecverde_is_principal() to authenticated;

-- Fonte canônica de autorização usada pelas RLS. SECURITY DEFINER evita
-- recursão na própria perfis_acesso; a identidade é sempre auth.uid().
create or replace function public.tecverde_can(
  p_modulo text,
  p_acao text default 'ver'
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    public.tecverde_is_gestao()
    or exists (
      select 1
        from public.perfis_acesso p
       where p.user_id = (select auth.uid())
         and public.tecverde_access_profile_active(p.status, p.suspended_until)
         and lower(coalesce(p.permissions -> p_modulo ->> p_acao, 'false')) = 'true'
    );
$$;

revoke all on function public.tecverde_can(text, text) from public, anon;
grant execute on function public.tecverde_can(text, text) to authenticated;

create or replace function public.tecverde_permissions_for_role(p_role text)
returns jsonb
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_role text := upper(coalesce(p_role, ''));
  v_permissions jsonb;
begin
  if v_role in ('ADMINISTRADOR', 'ADMIN', 'GESTOR', 'GESTÃO', 'GESTAO') then
    v_role := 'GESTAO';
  elsif v_role in ('SUPERVISOR', 'CONSULTA', 'LEITURA_GERAL') then
    v_role := 'LEITURA_GERAL';
  elsif v_role in ('OPERADOR', 'INSPETOR', 'QUALIDADE') then
    v_role := 'INSPETOR';
  end if;

  v_permissions := case v_role
    when 'GESTAO' then jsonb_build_object(
      'AUDITORIA', jsonb_build_object('ver', true, 'editar', true),
      'INDICADORES', jsonb_build_object('ver', true, 'editar', true),
      'HISTÓRICO', jsonb_build_object('ver', true, 'editar', true),
      'FORNECEDORES', jsonb_build_object('ver', true, 'editar', true),
      'DOCUMENTOS', jsonb_build_object('ver', true, 'editar', true),
      'NÃO CONFORMIDADES', jsonb_build_object('ver', true, 'editar', true),
      'PLANOS DE AÇÃO', jsonb_build_object('ver', true, 'editar', true),
      'CONTROLE DE PRODUÇÃO', jsonb_build_object('ver', true, 'editar', true),
      'SUPORTE', jsonb_build_object('ver', true, 'editar', true),
      'CONFIGURAÇÃO', jsonb_build_object('ver', true, 'editar', true),
      'CADASTROS', jsonb_build_object('ver', true, 'editar', true)
    )
    when 'LEITURA_GERAL' then jsonb_build_object(
      'AUDITORIA', jsonb_build_object('ver', true, 'editar', false),
      'INDICADORES', jsonb_build_object('ver', true, 'editar', false),
      'HISTÓRICO', jsonb_build_object('ver', true, 'editar', false),
      'FORNECEDORES', jsonb_build_object('ver', true, 'editar', false),
      'DOCUMENTOS', jsonb_build_object('ver', true, 'editar', false),
      'NÃO CONFORMIDADES', jsonb_build_object('ver', true, 'editar', false),
      'PLANOS DE AÇÃO', jsonb_build_object('ver', true, 'editar', false),
      'CONTROLE DE PRODUÇÃO', jsonb_build_object('ver', true, 'editar', false),
      'SUPORTE', jsonb_build_object('ver', true, 'editar', false),
      'CONFIGURAÇÃO', jsonb_build_object('ver', false, 'editar', false),
      'CADASTROS', jsonb_build_object('ver', false, 'editar', false)
    )
    when 'INDICADORES' then jsonb_build_object(
      'AUDITORIA', jsonb_build_object('ver', false, 'editar', false),
      'INDICADORES', jsonb_build_object('ver', true, 'editar', false),
      'HISTÓRICO', jsonb_build_object('ver', false, 'editar', false),
      'FORNECEDORES', jsonb_build_object('ver', false, 'editar', false),
      'DOCUMENTOS', jsonb_build_object('ver', false, 'editar', false),
      'NÃO CONFORMIDADES', jsonb_build_object('ver', false, 'editar', false),
      'PLANOS DE AÇÃO', jsonb_build_object('ver', false, 'editar', false),
      'CONTROLE DE PRODUÇÃO', jsonb_build_object('ver', false, 'editar', false),
      'SUPORTE', jsonb_build_object('ver', false, 'editar', false),
      'CONFIGURAÇÃO', jsonb_build_object('ver', false, 'editar', false),
      'CADASTROS', jsonb_build_object('ver', false, 'editar', false)
    )
    when 'INSPETOR' then jsonb_build_object(
      'AUDITORIA', jsonb_build_object('ver', true, 'editar', true),
      'INDICADORES', jsonb_build_object('ver', true, 'editar', false),
      'HISTÓRICO', jsonb_build_object('ver', false, 'editar', false),
      'FORNECEDORES', jsonb_build_object('ver', true, 'editar', false),
      'DOCUMENTOS', jsonb_build_object('ver', true, 'editar', false),
      'NÃO CONFORMIDADES', jsonb_build_object('ver', true, 'editar', true),
      'PLANOS DE AÇÃO', jsonb_build_object('ver', true, 'editar', true),
      'CONTROLE DE PRODUÇÃO', jsonb_build_object('ver', true, 'editar', true),
      'SUPORTE', jsonb_build_object('ver', true, 'editar', false),
      'CONFIGURAÇÃO', jsonb_build_object('ver', false, 'editar', false),
      'CADASTROS', jsonb_build_object('ver', false, 'editar', false)
    )
    else '{}'::jsonb
  end;

  return v_permissions;
end;
$$;

revoke all on function public.tecverde_permissions_for_role(text) from public, anon;
grant execute on function public.tecverde_permissions_for_role(text) to authenticated;

-- A aplicação já usa public.profiles como view coarse-grained. Mantemos a
-- compatibilidade, mas fazemos a view obedecer à RLS da perfis_acesso.
create or replace view public.profiles
with (security_invoker = true)
as
select
  p.user_id as id,
  coalesce(nullif(trim(p.full_name), ''), split_part(p.email, '@', 1)) as nome,
  case
    when upper(coalesce(p.role, '')) in ('ADMINISTRADOR', 'ADMIN', 'GESTOR', 'GESTÃO', 'GESTAO') then 'gestao'::text
    when upper(coalesce(p.role, '')) in ('OPERADOR', 'INSPETOR', 'AUDITOR', 'QUALIDADE') then 'operador'::text
    else 'consultor'::text
  end as role
from public.perfis_acesso p
where p.user_id is not null
  and public.tecverde_access_profile_active(p.status, p.suspended_until);

grant select on public.profiles to authenticated;

create or replace function public.tecverde_governanca_touch()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  if tg_table_name = 'perfis_acesso' then
    new.version := coalesce(old.version, 0) + 1;
  end if;
  return new;
end;
$$;

revoke all on function public.tecverde_governanca_touch() from public, anon;

DROP TRIGGER IF EXISTS perfis_acesso_governanca_touch ON public.perfis_acesso;
create trigger perfis_acesso_governanca_touch
before update on public.perfis_acesso
for each row execute function public.tecverde_governanca_touch();

DROP TRIGGER IF EXISTS equipes_governanca_touch ON public.equipes;
create trigger equipes_governanca_touch
before update on public.equipes
for each row execute function public.tecverde_governanca_touch();

create or replace function public.tecverde_governanca_audit_trigger()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row jsonb;
  v_id text;
begin
  if tg_op = 'DELETE' then
    v_row := to_jsonb(old);
  else
    v_row := to_jsonb(new);
  end if;

  if tg_table_name = 'equipe_membros' then
    v_id := coalesce(v_row ->> 'equipe_id', '') || ':' || coalesce(v_row ->> 'user_id', '');
  else
    v_id := coalesce(v_row ->> 'id', v_row ->> 'user_id');
  end if;

  insert into public.governanca_audit_log (
    actor_id, acao, entidade, entidade_id, antes, depois
  ) values (
    auth.uid(),
    tg_op,
    tg_table_name,
    v_id,
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end
  );

  return null;
end;
$$;

revoke all on function public.tecverde_governanca_audit_trigger() from public, anon;

DROP TRIGGER IF EXISTS perfis_acesso_governanca_audit ON public.perfis_acesso;
create trigger perfis_acesso_governanca_audit
after insert or update or delete on public.perfis_acesso
for each row execute function public.tecverde_governanca_audit_trigger();

DROP TRIGGER IF EXISTS equipes_governanca_audit ON public.equipes;
create trigger equipes_governanca_audit
after insert or update or delete on public.equipes
for each row execute function public.tecverde_governanca_audit_trigger();

DROP TRIGGER IF EXISTS equipe_membros_governanca_audit ON public.equipe_membros;
create trigger equipe_membros_governanca_audit
after insert or update or delete on public.equipe_membros
for each row execute function public.tecverde_governanca_audit_trigger();

DROP TRIGGER IF EXISTS obras_projetos_governanca_audit ON public.obras_projetos;
create trigger obras_projetos_governanca_audit
after insert or update or delete on public.obras_projetos
for each row execute function public.tecverde_governanca_audit_trigger();

create or replace function public.governanca_registrar_evento(
  p_acao text,
  p_entidade text,
  p_entidade_id text default null,
  p_antes jsonb default null,
  p_depois jsonb default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.tecverde_is_gestao() then
    raise exception 'Acesso restrito à Gestão' using errcode = '42501';
  end if;

  insert into public.governanca_audit_log (
    actor_id, acao, entidade, entidade_id, antes, depois
  ) values (
    auth.uid(), p_acao, p_entidade, p_entidade_id, p_antes, p_depois
  );
end;
$$;

revoke all on function public.governanca_registrar_evento(text, text, text, jsonb, jsonb) from public, anon;
grant execute on function public.governanca_registrar_evento(text, text, text, jsonb, jsonb) to authenticated;

-- Perfis de acesso: cada usuário lê o próprio perfil; somente Gestão altera.
DROP POLICY IF EXISTS "TECVERDE_perfis_select" ON public.perfis_acesso;
DROP POLICY IF EXISTS "TECVERDE_perfis_insert_admin" ON public.perfis_acesso;
DROP POLICY IF EXISTS "TECVERDE_perfis_update_admin" ON public.perfis_acesso;
DROP POLICY IF EXISTS "TECVERDE_perfis_delete_admin" ON public.perfis_acesso;
DROP POLICY IF EXISTS perfis_select_self_or_gestao ON public.perfis_acesso;
DROP POLICY IF EXISTS perfis_insert_gestao ON public.perfis_acesso;
DROP POLICY IF EXISTS perfis_update_gestao ON public.perfis_acesso;
DROP POLICY IF EXISTS perfis_delete_gestao ON public.perfis_acesso;

create policy perfis_select_self_or_gestao
on public.perfis_acesso
for select
to authenticated
using (
  public.tecverde_is_gestao()
  or user_id = (select auth.uid())
  or lower(email) = public.tecverde_email_atual()
);

create policy perfis_insert_gestao
on public.perfis_acesso
for insert
to authenticated
with check (public.tecverde_is_gestao());

create policy perfis_update_gestao
on public.perfis_acesso
for update
to authenticated
using (public.tecverde_is_gestao())
with check (public.tecverde_is_gestao());

create policy perfis_delete_gestao
on public.perfis_acesso
for delete
to authenticated
using (public.tecverde_is_gestao());

DROP POLICY IF EXISTS "TECVERDE_solicitacoes_select" ON public.solicitacoes_acesso;
DROP POLICY IF EXISTS "TECVERDE_solicitacoes_insert" ON public.solicitacoes_acesso;
DROP POLICY IF EXISTS "TECVERDE_solicitacoes_update_admin" ON public.solicitacoes_acesso;
DROP POLICY IF EXISTS "TECVERDE_solicitacoes_delete_admin" ON public.solicitacoes_acesso;
DROP POLICY IF EXISTS solicitacoes_select_self_or_gestao ON public.solicitacoes_acesso;
DROP POLICY IF EXISTS solicitacoes_insert_self_or_gestao ON public.solicitacoes_acesso;
DROP POLICY IF EXISTS solicitacoes_update_gestao ON public.solicitacoes_acesso;
DROP POLICY IF EXISTS solicitacoes_delete_gestao ON public.solicitacoes_acesso;

create policy solicitacoes_select_self_or_gestao
on public.solicitacoes_acesso
for select
to authenticated
using (
  public.tecverde_is_gestao()
  or user_id = (select auth.uid())
  or lower(email) = public.tecverde_email_atual()
);

create policy solicitacoes_insert_self_or_gestao
on public.solicitacoes_acesso
for insert
to authenticated
with check (
  public.tecverde_is_gestao()
  or (
    user_id = (select auth.uid())
    and lower(email) = public.tecverde_email_atual()
  )
);

create policy solicitacoes_update_gestao
on public.solicitacoes_acesso
for update
to authenticated
using (public.tecverde_is_gestao())
with check (public.tecverde_is_gestao());

create policy solicitacoes_delete_gestao
on public.solicitacoes_acesso
for delete
to authenticated
using (public.tecverde_is_gestao());

alter table public.equipes enable row level security;
alter table public.equipe_membros enable row level security;
alter table public.governanca_audit_log enable row level security;

DROP POLICY IF EXISTS equipes_gestao_all ON public.equipes;
create policy equipes_gestao_all
on public.equipes
for all
to authenticated
using (public.tecverde_is_gestao())
with check (public.tecverde_is_gestao());

DROP POLICY IF EXISTS equipe_membros_gestao_all ON public.equipe_membros;
create policy equipe_membros_gestao_all
on public.equipe_membros
for all
to authenticated
using (public.tecverde_is_gestao())
with check (public.tecverde_is_gestao());

DROP POLICY IF EXISTS governanca_audit_select_gestao ON public.governanca_audit_log;
create policy governanca_audit_select_gestao
on public.governanca_audit_log
for select
to authenticated
using (public.tecverde_is_gestao());

grant select, insert, update, delete on public.equipes to authenticated;
grant select, insert, update, delete on public.equipe_membros to authenticated;
grant select on public.governanca_audit_log to authenticated;
revoke insert, update, delete on public.governanca_audit_log from authenticated, anon;

commit;
