-- Módulo de Cadastros e Governança de Acessos
-- Mantém compatibilidade com as permissões existentes e remove a dependência
-- de um e-mail fixo para administrar o sistema.

begin;

alter table public.perfis_acesso
  add column if not exists suspended_until timestamptz,
  add column if not exists version bigint not null default 1;

create index if not exists perfis_acesso_role_status_idx
  on public.perfis_acesso (role, status);

create table if not exists public.equipes (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  descricao text,
  ativo boolean not null default true,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists equipes_nome_uq
  on public.equipes (lower(nome));

create index if not exists equipes_ativo_nome_idx
  on public.equipes (ativo, nome);

create table if not exists public.equipe_membros (
  equipe_id uuid not null references public.equipes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  papel_equipe text not null default 'MEMBRO',
  created_at timestamptz not null default now(),
  primary key (equipe_id, user_id)
);

create index if not exists equipe_membros_user_idx
  on public.equipe_membros (user_id, equipe_id);

create table if not exists public.governanca_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid,
  acao text not null,
  entidade text not null,
  entidade_id text,
  antes jsonb,
  depois jsonb,
  created_at timestamptz not null default now()
);

create index if not exists governanca_audit_created_idx
  on public.governanca_audit_log (created_at desc);
create index if not exists governanca_audit_actor_idx
  on public.governanca_audit_log (actor_id, created_at desc);
create index if not exists governanca_audit_entidade_idx
  on public.governanca_audit_log (entidade, entidade_id, created_at desc);

-- A tabela profiles é usada pela UI como papel coarse-grained. Ela já contém
-- um registro único por usuário; formalizamos isso para poder sincronizá-la
-- com perfis_acesso com segurança.
do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conrelid = 'public.profiles'::regclass
       and contype = 'p'
  ) then
    alter table public.profiles alter column id set not null;
    alter table public.profiles add constraint profiles_pkey primary key (id);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conrelid = 'public.profiles'::regclass
       and conname = 'profiles_id_fkey'
  ) then
    alter table public.profiles
      add constraint profiles_id_fkey
      foreign key (id) references auth.users(id) on delete cascade;
  end if;
end
$$;

create or replace function public.tecverde_access_profile_active(
  p_status text,
  p_suspended_until timestamptz
)
returns boolean
language sql
stable
set search_path = ''
as $$
  select
    upper(coalesce(p_status, '')) = 'APROVADO'
    or (
      upper(coalesce(p_status, '')) = 'SUSPENSO'
      and p_suspended_until is not null
      and p_suspended_until <= now()
    );
$$;

create or replace function public.tecverde_is_gestao()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
      from public.perfis_acesso p
     where p.user_id = (select auth.uid())
       and upper(coalesce(p.role, '')) in ('GESTAO', 'ADMINISTRADOR')
       and public.tecverde_access_profile_active(p.status, p.suspended_until)
  );
$$;

revoke all on function public.tecverde_is_gestao() from public;
grant execute on function public.tecverde_is_gestao() to authenticated;

-- Compatibilidade: centenas de policies/RPCs existentes já chamam
-- tecverde_is_principal(). A implementação passa a significar Gestão,
-- sem hard-code de identidade individual.
create or replace function public.tecverde_is_principal()
returns boolean
language sql
stable
set search_path = ''
as $$
  select public.tecverde_is_gestao();
$$;

revoke all on function public.tecverde_is_principal() from public;
grant execute on function public.tecverde_is_principal() to authenticated;

-- Leitura canônica de permissão usada pela RLS. SECURITY DEFINER é intencional:
-- evita recursão nas policies de perfis_acesso; a função só responde sobre o
-- auth.uid() corrente e não aceita identidade arbitrária como parâmetro.
create or replace function public.tecverde_can(
  p_modulo text,
  p_acao text default 'ver'
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    public.tecverde_is_gestao()
    or exists (
      select 1
        from public.perfis_acesso p
       where p.user_id = (select auth.uid())
         and public.tecverde_access_profile_active(p.status, p.suspended_until)
         and lower(coalesce(p.permissions -> p_modulo ->> p_acao, 'false')) = 'true'
    );
$$;

revoke all on function public.tecverde_can(text, text) from public;
grant execute on function public.tecverde_can(text, text) to authenticated;

create or replace function public.tecverde_permissions_for_role(p_role text)
returns jsonb
language sql
immutable
set search_path = ''
as $$
  select case upper(coalesce(p_role, ''))
    when 'GESTAO' then jsonb_build_object(
      'AUDITORIA', jsonb_build_object('ver', true, 'editar', true),
      'INDICADORES', jsonb_build_object('ver', true, 'editar', true),
      'HISTÓRICO', jsonb_build_object('ver', true, 'editar', true),
      'FORNECEDORES', jsonb_build_object('ver', true, 'editar', true),
      'DOCUMENTOS', jsonb_build_object('ver', true, 'editar', true),
      'NÃO CONFORMIDADES', jsonb_build_object('ver', true, 'editar', true),
      'PLANOS DE AÇÃO', jsonb_build_object('ver', true, 'editar', true),
      'CONTROLE DE PRODUÇÃO', jsonb_build_object('ver', true, 'editar', true),
      'SUPORTE', jsonb_build_object('ver', true, 'editar', true),
      'CONFIGURAÇÃO', jsonb_build_object('ver', true, 'editar', true),
      'CADASTROS', jsonb_build_object('ver', true, 'editar', true)
    )
    when 'LEITURA_GERAL' then jsonb_build_object(
      'AUDITORIA', jsonb_build_object('ver', true, 'editar', false),
      'INDICADORES', jsonb_build_object('ver', true, 'editar', false),
      'HISTÓRICO', jsonb_build_object('ver', true, 'editar', false),
      'FORNECEDORES', jsonb_build_object('ver', true, 'editar', false),
      'DOCUMENTOS', jsonb_build_object('ver', true, 'editar', false),
      'NÃO CONFORMIDADES', jsonb_build_object('ver', true, 'editar', false),
      'PLANOS DE AÇÃO', jsonb_build_object('ver', true, 'editar', false),
      'CONTROLE DE PRODUÇÃO', jsonb_build_object('ver', true, 'editar', false),
      'SUPORTE', jsonb_build_object('ver', true, 'editar', false),
      'CONFIGURAÇÃO', jsonb_build_object('ver', false, 'editar', false),
      'CADASTROS', jsonb_build_object('ver', false, 'editar', false)
    )
    when 'INDICADORES' then jsonb_build_object(
      'AUDITORIA', jsonb_build_object('ver', false, 'editar', false),
      'INDICADORES', jsonb_build_object('ver', true, 'editar', false),
      'HISTÓRICO', jsonb_build_object('ver', false, 'editar', false),
      'FORNECEDORES', jsonb_build_object('ver', false, 'editar', false),
      'DOCUMENTOS', jsonb_build_object('ver', false, 'editar', false),
      'NÃO CONFORMIDADES', jsonb_build_object('ver', false, 'editar', false),
      'PLANOS DE AÇÃO', jsonb_build_object('ver', false, 'editar', false),
      'CONTROLE DE PRODUÇÃO', jsonb_build_object('ver', false, 'editar', false),
      'SUPORTE', jsonb_build_object('ver', false, 'editar', false),
      'CONFIGURAÇÃO', jsonb_build_object('ver', false, 'editar', false),
      'CADASTROS', jsonb_build_object('ver', false, 'editar', false)
    )
    when 'INSPETOR' then jsonb_build_object(
      'AUDITORIA', jsonb_build_object('ver', true, 'editar', true),
      'INDICADORES', jsonb_build_object('ver', true, 'editar', false),
      'HISTÓRICO', jsonb_build_object('ver', false, 'editar', false),
      'FORNECEDORES', jsonb_build_object('ver', true, 'editar', false),
      'DOCUMENTOS', jsonb_build_object('ver', true, 'editar', false),
      'NÃO CONFORMIDADES', jsonb_build_object('ver', true, 'editar', true),
      'PLANOS DE AÇÃO', jsonb_build_object('ver', true, 'editar', true),
      'CONTROLE DE PRODUÇÃO', jsonb_build_object('ver', true, 'editar', true),
      'SUPORTE', jsonb_build_object('ver', true, 'editar', false),
      'CONFIGURAÇÃO', jsonb_build_object('ver', false, 'editar', false),
      'CADASTROS', jsonb_build_object('ver', false, 'editar', false)
    )
    when 'OPERADOR' then public.tecverde_permissions_for_role('INSPETOR')
    when 'SUPERVISOR' then public.tecverde_permissions_for_role('LEITURA_GERAL')
    when 'CONSULTA' then public.tecverde_permissions_for_role('LEITURA_GERAL')
    else '{}'::jsonb
  end;
$$;

revoke all on function public.tecverde_permissions_for_role(text) from public;
grant execute on function public.tecverde_permissions_for_role(text) to authenticated;

create or replace function public.tecverde_governanca_touch()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  if tg_table_name = 'perfis_acesso' then
    new.version := coalesce(old.version, 0) + 1;
  end if;
  return new;
end;
$$;

revoke all on function public.tecverde_governanca_touch() from public;

DROP TRIGGER IF EXISTS perfis_acesso_governanca_touch ON public.perfis_acesso;
create trigger perfis_acesso_governanca_touch
before update on public.perfis_acesso
for each row execute function public.tecverde_governanca_touch();

DROP TRIGGER IF EXISTS equipes_governanca_touch ON public.equipes;
create trigger equipes_governanca_touch
before update on public.equipes
for each row execute function public.tecverde_governanca_touch();

create or replace function public.tecverde_sync_profile_from_access()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
begin
  if new.user_id is null then
    return new;
  end if;

  v_role := case
    when upper(coalesce(new.role, '')) in ('GESTAO', 'ADMINISTRADOR') then 'gestao'
    when upper(coalesce(new.role, '')) in ('LEITURA_GERAL', 'INDICADORES', 'CONSULTA', 'SUPERVISOR') then 'consultor'
    else 'operador'
  end;

  insert into public.profiles (id, nome, role)
  values (new.user_id, coalesce(nullif(new.full_name, ''), new.email), v_role)
  on conflict (id) do update
    set nome = excluded.nome,
        role = excluded.role;

  return new;
end;
$$;

revoke all on function public.tecverde_sync_profile_from_access() from public;

DROP TRIGGER IF EXISTS perfis_acesso_sync_profile ON public.perfis_acesso;
create trigger perfis_acesso_sync_profile
after insert or update of user_id, full_name, role on public.perfis_acesso
for each row execute function public.tecverde_sync_profile_from_access();

-- Sincroniza os dois perfis existentes sem alterar permissões granulares.
insert into public.profiles (id, nome, role)
select
  p.user_id,
  coalesce(nullif(p.full_name, ''), p.email),
  case
    when upper(coalesce(p.role, '')) in ('GESTAO', 'ADMINISTRADOR') then 'gestao'
    when upper(coalesce(p.role, '')) in ('LEITURA_GERAL', 'INDICADORES', 'CONSULTA', 'SUPERVISOR') then 'consultor'
    else 'operador'
  end
from public.perfis_acesso p
where p.user_id is not null
on conflict (id) do update
set nome = excluded.nome,
    role = excluded.role;

create or replace function public.tecverde_governanca_audit_trigger()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id text;
begin
  v_id := case
    when tg_table_name = 'equipe_membros' then
      coalesce((to_jsonb(coalesce(new, old)) ->> 'equipe_id'), '') || ':' ||
      coalesce((to_jsonb(coalesce(new, old)) ->> 'user_id'), '')
    else
      to_jsonb(coalesce(new, old)) ->> 'id'
  end;

  insert into public.governanca_audit_log (
    actor_id, acao, entidade, entidade_id, antes, depois
  ) values (
    auth.uid(),
    tg_op,
    tg_table_name,
    v_id,
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end
  );

  return coalesce(new, old);
end;
$$;

revoke all on function public.tecverde_governanca_audit_trigger() from public;

DROP TRIGGER IF EXISTS equipes_governanca_audit ON public.equipes;
create trigger equipes_governanca_audit
after insert or update or delete on public.equipes
for each row execute function public.tecverde_governanca_audit_trigger();

DROP TRIGGER IF EXISTS equipe_membros_governanca_audit ON public.equipe_membros;
create trigger equipe_membros_governanca_audit
after insert or update or delete on public.equipe_membros
for each row execute function public.tecverde_governanca_audit_trigger();

DROP TRIGGER IF EXISTS obras_projetos_governanca_audit ON public.obras_projetos;
create trigger obras_projetos_governanca_audit
after insert or update or delete on public.obras_projetos
for each row execute function public.tecverde_governanca_audit_trigger();

create or replace function public.governanca_registrar_evento(
  p_acao text,
  p_entidade text,
  p_entidade_id text default null,
  p_antes jsonb default null,
  p_depois jsonb default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.tecverde_is_gestao() then
    raise exception 'Acesso restrito à Gestão' using errcode = '42501';
  end if;

  insert into public.governanca_audit_log (
    actor_id, acao, entidade, entidade_id, antes, depois
  ) values (
    auth.uid(), p_acao, p_entidade, p_entidade_id, p_antes, p_depois
  );
end;
$$;

revoke all on function public.governanca_registrar_evento(text, text, text, jsonb, jsonb) from public;
grant execute on function public.governanca_registrar_evento(text, text, text, jsonb, jsonb) to authenticated;

-- RLS do perfil coarse-grained: antes estava sem RLS.
alter table public.profiles enable row level security;

DROP POLICY IF EXISTS profiles_select_self_or_gestao ON public.profiles;
create policy profiles_select_self_or_gestao
on public.profiles
for select
to authenticated
using (id = (select auth.uid()) or public.tecverde_is_gestao());

DROP POLICY IF EXISTS profiles_insert_gestao ON public.profiles;
create policy profiles_insert_gestao
on public.profiles
for insert
to authenticated
with check (public.tecverde_is_gestao());

DROP POLICY IF EXISTS profiles_update_gestao ON public.profiles;
create policy profiles_update_gestao
on public.profiles
for update
to authenticated
using (public.tecverde_is_gestao())
with check (public.tecverde_is_gestao());

DROP POLICY IF EXISTS profiles_delete_gestao ON public.profiles;
create policy profiles_delete_gestao
on public.profiles
for delete
to authenticated
using (public.tecverde_is_gestao());

-- Perfis de acesso: o próprio usuário pode ler o seu; somente Gestão altera.
DROP POLICY IF EXISTS "TECVERDE_perfis_select" ON public.perfis_acesso;
DROP POLICY IF EXISTS "TECVERDE_perfis_insert_admin" ON public.perfis_acesso;
DROP POLICY IF EXISTS "TECVERDE_perfis_update_admin" ON public.perfis_acesso;
DROP POLICY IF EXISTS "TECVERDE_perfis_delete_admin" ON public.perfis_acesso;
DROP POLICY IF EXISTS perfis_select_self_or_gestao ON public.perfis_acesso;
DROP POLICY IF EXISTS perfis_insert_gestao ON public.perfis_acesso;
DROP POLICY IF EXISTS perfis_update_gestao ON public.perfis_acesso;
DROP POLICY IF EXISTS perfis_delete_gestao ON public.perfis_acesso;

create policy perfis_select_self_or_gestao
on public.perfis_acesso
for select
to authenticated
using (
  public.tecverde_is_gestao()
  or user_id = (select auth.uid())
  or lower(email) = public.tecverde_email_atual()
);

create policy perfis_insert_gestao
on public.perfis_acesso
for insert
to authenticated
with check (public.tecverde_is_gestao());

create policy perfis_update_gestao
on public.perfis_acesso
for update
to authenticated
using (public.tecverde_is_gestao())
with check (public.tecverde_is_gestao());

create policy perfis_delete_gestao
on public.perfis_acesso
for delete
to authenticated
using (public.tecverde_is_gestao());

-- Solicitações seguem a mesma fronteira administrativa, preservando o
-- autoatendimento de leitura/criação da própria solicitação.
DROP POLICY IF EXISTS "TECVERDE_solicitacoes_select" ON public.solicitacoes_acesso;
DROP POLICY IF EXISTS "TECVERDE_solicitacoes_insert" ON public.solicitacoes_acesso;
DROP POLICY IF EXISTS "TECVERDE_solicitacoes_update_admin" ON public.solicitacoes_acesso;
DROP POLICY IF EXISTS "TECVERDE_solicitacoes_delete_admin" ON public.solicitacoes_acesso;

create policy solicitacoes_select_self_or_gestao
on public.solicitacoes_acesso
for select
to authenticated
using (
  public.tecverde_is_gestao()
  or user_id = (select auth.uid())
  or lower(email) = public.tecverde_email_atual()
);

create policy solicitacoes_insert_self_or_gestao
on public.solicitacoes_acesso
for insert
to authenticated
with check (
  public.tecverde_is_gestao()
  or (
    user_id = (select auth.uid())
    and lower(email) = public.tecverde_email_atual()
  )
);

create policy solicitacoes_update_gestao
on public.solicitacoes_acesso
for update
to authenticated
using (public.tecverde_is_gestao())
with check (public.tecverde_is_gestao());

create policy solicitacoes_delete_gestao
on public.solicitacoes_acesso
for delete
to authenticated
using (public.tecverde_is_gestao());

alter table public.equipes enable row level security;
alter table public.equipe_membros enable row level security;
alter table public.governanca_audit_log enable row level security;

DROP POLICY IF EXISTS equipes_gestao_all ON public.equipes;
create policy equipes_gestao_all
on public.equipes
for all
to authenticated
using (public.tecverde_is_gestao())
with check (public.tecverde_is_gestao());

DROP POLICY IF EXISTS equipe_membros_gestao_all ON public.equipe_membros;
create policy equipe_membros_gestao_all
on public.equipe_membros
for all
to authenticated
using (public.tecverde_is_gestao())
with check (public.tecverde_is_gestao());

DROP POLICY IF EXISTS governanca_audit_select_gestao ON public.governanca_audit_log;
create policy governanca_audit_select_gestao
on public.governanca_audit_log
for select
to authenticated
using (public.tecverde_is_gestao());

grant select, insert, update, delete on public.equipes to authenticated;
grant select, insert, update, delete on public.equipe_membros to authenticated;
grant select on public.governanca_audit_log to authenticated;
revoke insert, update, delete on public.governanca_audit_log from authenticated, anon;

commit;
